name: Scanner CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make scanner
      run: |
        chmod +x ../binaries/ptc
        mkdir -p /opt/caslab/lib/pt
        cp -r ../base-files/. /opt/caslab/lib/pt/
        export PATH=$PATH:$(pwd)/../binaries
        make scanner
      working-directory: ./pt

