name: Scanner CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install 32bit libs
      run: sudo apt-get install gcc-multilib lib32z1-dev
    - name: make scanner
      run: |
        chmod +x ../binaries/ptc
        chmod +x ../binaries/ssl
        chmod +x ../binaries/ssltrace
        
        mkdir -p /opt/caslab/lib/
        cp -r ../base-files/. /opt/caslab/lib/
        chmod -R 755 /opt/caslab/lib/

        export PATH=$PATH:$(pwd)/../binaries

        make scanner
        ssl parser/scanner.ssl
      working-directory: ./pt
    
    - name: Test scanner (scanTest.qu)
      run: |
        chmod +x ../binaries/ptc
        chmod +x ../binaries/ssl
        chmod +x ../binaries/ssltrace

        export PATH=$PATH:$(pwd)/../binaries
        rm -rf lib/
        mkdir -p lib/pt/
        
        make scanner
        
        make scanner

        cp ./test/scanTest.qu ./test/scanTest.pt
        timeout 3 ssltrace "ptc -o1 -t1 -L lib/pt ./test/scanTest.pt" lib/pt/scan.def -e; echo exit=$
      working-directory: ./pt
    
    - name: Test scanner (simpleTest.qu)
      run: |
        chmod +x ../binaries/ptc
        chmod +x ../binaries/ssl
        chmod +x ../binaries/ssltrace

        export PATH=$PATH:$(pwd)/../binaries

        make scanner
        
        cp ./test/simpleTest.qu ./test/simpleTest.pt
        timeout 3 ssltrace "ptc -o1 -t1 -L lib/pt ./test/simpleTest.pt" lib/pt/scan.def -e; echo exit=$
      working-directory: ./pt
    
    - name: Test scanner (test.qu)
      run: |
        chmod +x ../binaries/ptc
        chmod +x ../binaries/ssl
        chmod +x ../binaries/ssltrace

        cp -r ../base-files/. /opt/caslab/lib/
        chmod -R 755 /opt/caslab/lib/
        export PATH=$PATH:$(pwd)/../binaries
        
        make scanner
        
        cp ./test/test.qu ./test/test.pt
        timeout 3 ssltrace "ptc -o1 -t1 -L lib/pt ./test/test.pt" lib/pt/scan.def -e; echo exit=$
      working-directory: ./pt



