name: Scanner CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: set path variables
      run: | 
        chmod -x ./binaries/ptc
        ls -la /binaries
        export PATH=$PATH:$(pwd)/binaries
        $PATH
    - name: make scanner
      run: make scanner
      working-directory: ./pt

